// <auto-generated />
using System;
using APBD10.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APBD10.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260514205545_CascadeDeleteOnPc")]
    partial class CascadeDeleteOnPc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APBD10.Entities.Component", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("char(10)");

                    b.Property<int>("ComponentManufacturerId")
                        .HasColumnType("int");

                    b.Property<int>("ComponentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Code");

                    b.HasIndex("ComponentManufacturerId");

                    b.HasIndex("ComponentTypeId");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            Code = "INT-I9-139",
                            ComponentManufacturerId = 1,
                            ComponentTypeId = 1,
                            Description = "24-core, 32-thread desktop processor",
                            Name = "Intel Core i9-13900K"
                        },
                        new
                        {
                            Code = "AMD-R9-795",
                            ComponentManufacturerId = 2,
                            ComponentTypeId = 1,
                            Description = "16-core, 32-thread desktop processor",
                            Name = "AMD Ryzen 9 7950X"
                        },
                        new
                        {
                            Code = "NV-RTX4090",
                            ComponentManufacturerId = 3,
                            ComponentTypeId = 2,
                            Description = "24GB GDDR6X flagship GPU",
                            Name = "NVIDIA GeForce RTX 4090"
                        },
                        new
                        {
                            Code = "COR-32G-D5",
                            ComponentManufacturerId = 4,
                            ComponentTypeId = 3,
                            Description = "2x16GB DDR5 5600MHz RAM",
                            Name = "Corsair Vengeance 32GB"
                        });
                });

            modelBuilder.Entity("APBD10.Entities.ComponentManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateOnly>("FoundationDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("ComponentManufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "Intel",
                            FoundationDate = new DateOnly(1968, 7, 18),
                            FullName = "Intel Corporation"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "AMD",
                            FoundationDate = new DateOnly(1969, 5, 1),
                            FullName = "Advanced Micro Devices, Inc."
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "NVIDIA",
                            FoundationDate = new DateOnly(1993, 4, 5),
                            FullName = "NVIDIA Corporation"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "Corsair",
                            FoundationDate = new DateOnly(1994, 1, 1),
                            FullName = "Corsair Gaming, Inc."
                        });
                });

            modelBuilder.Entity("APBD10.Entities.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CPU",
                            Name = "Central Processing Unit"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "GPU",
                            Name = "Graphics Processing Unit"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "RAM",
                            Name = "Random Access Memory"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "MB",
                            Name = "Motherboard"
                        });
                });

            modelBuilder.Entity("APBD10.Entities.Pc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("float(5)");

                    b.HasKey("Id");

                    b.ToTable("PC");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 10, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Titan Build",
                            Stock = 5,
                            Warranty = 24,
                            Weight = 12.5f
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 10, 2, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ryzen Workstation",
                            Stock = 3,
                            Warranty = 36,
                            Weight = 14f
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 10, 5, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            Name = "Budget Gamer",
                            Stock = 10,
                            Warranty = 12,
                            Weight = 9.5f
                        });
                });

            modelBuilder.Entity("APBD10.Entities.PcComponent", b =>
                {
                    b.Property<int>("PcId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentCode")
                        .HasColumnType("char(10)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("PcId", "ComponentCode");

                    b.HasIndex("ComponentCode");

                    b.ToTable("PcComponents");

                    b.HasData(
                        new
                        {
                            PcId = 1,
                            ComponentCode = "INT-I9-139",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 1,
                            ComponentCode = "NV-RTX4090",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 1,
                            ComponentCode = "COR-32G-D5",
                            Amount = 2
                        },
                        new
                        {
                            PcId = 2,
                            ComponentCode = "AMD-R9-795",
                            Amount = 1
                        });
                });

            modelBuilder.Entity("APBD10.Entities.Component", b =>
                {
                    b.HasOne("APBD10.Entities.ComponentManufacturer", "ComponentManufacturer")
                        .WithMany()
                        .HasForeignKey("ComponentManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBD10.Entities.ComponentType", "ComponentType")
                        .WithMany("Components")
                        .HasForeignKey("ComponentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentManufacturer");

                    b.Navigation("ComponentType");
                });

            modelBuilder.Entity("APBD10.Entities.PcComponent", b =>
                {
                    b.HasOne("APBD10.Entities.Component", "Component")
                        .WithMany("PcComponents")
                        .HasForeignKey("ComponentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBD10.Entities.Pc", "Pc")
                        .WithMany("PcComponents")
                        .HasForeignKey("PcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Pc");
                });

            modelBuilder.Entity("APBD10.Entities.Component", b =>
                {
                    b.Navigation("PcComponents");
                });

            modelBuilder.Entity("APBD10.Entities.ComponentType", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("APBD10.Entities.Pc", b =>
                {
                    b.Navigation("PcComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
